#include "WinFind.h"
#include "Config.h"
WinFind::WinFind()
{
	Config C = Config();
	WESTRING_COD_TYPE_STRINGstr = C.WESTRING_COD_TYPE_STRING();//字符串
	WESTRING_UE_DLG_EDITVALUEstr = C.WESTRING_UE_DLG_EDITVALUE();//编辑单位值 - %s
	WESTRING_IE_DLG_EDITVALUEstr = C.WESTRING_IE_DLG_EDITVALUE();//编辑物品值 - %s
	WESTRING_AE_DLG_EDITVALUEstr = C.WESTRING_AE_DLG_EDITVALUE();//编辑技能值 - %s
	WESTRING_FE_DLG_EDITVALUEstr = C.WESTRING_FE_DLG_EDITVALUE();//编辑效果值 - %s
	WESTRING_BE_DLG_EDITVALUEstr = C.WESTRING_BE_DLG_EDITVALUE();//编辑可破坏物值 - %s
	WESTRING_DE_DLG_EDITVALUEstr = C.WESTRING_DE_DLG_EDITVALUE();//编辑装饰物值 - %s
	WESTRING_GE_DLG_EDITVALUEstr = C.WESTRING_GE_DLG_EDITVALUE();//编辑科技值 - %s
}

